# Generated by Django 5.1 on 2024-08-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=221)),
                ('image', models.ImageField(upload_to='images/')),
                ('author_image', models.ImageField(upload_to='images_author/')),
                ('author_full_name', models.CharField(max_length=221)),
                ('author_position', models.CharField(max_length=221)),
            ],
        ),
    ]
